"""Compact figure index built entirely from saved prior-round metrics."""
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
ROOT=Path(__file__).resolve().parents[1];SRC=ROOT/'testing/outputs';OUT=SRC/'luke_motion_overnight_figure_index_v1'
def main():
 OUT.mkdir(exist_ok=True);fig,ax=plt.subplots(3,2,figsize=(14,13),layout='constrained');blue='#2878b5';pink='#b13775'
 d=pd.read_csv(SRC/'luke_3sigma_lowpass_screen_v2/scores.csv');d=d[d.name!='flat_zero_control'];labels=['Broad','Broad screen','LP fixed','LP fixed screen','LP adjusted','LP adj screen'];i=np.arange(len(d))
 a=ax[0,0];a.barh(i-.18,d.overall_mae_um,.35,color=blue,label='Overall');a.barh(i+.18,d.movement_mae_um,.35,color=pink,label='Drop/recovery');a.set(yticks=i,yticklabels=labels,xlabel='Provisional lighthouse disagreement (µm)',title='A · Low-pass / screening do not earn promotion');a.invert_yaxis();a.legend(fontsize=8)
 d=pd.read_csv(SRC/'luke_lowpass_common_events_v2/scores.csv');d=d[d.role=='factorial'];a=ax[0,1];a.bar(np.arange(4),d.overall_mae_um,color=[blue,pink,pink,pink]);a.set(xticks=np.arange(4),xticklabels=['Broad A/L','LP amp','LP loc','LP A/L'],ylabel='Overall disagreement (µm)',title='B · Amplitude + localization matter at fixed events');a.text(.03,.95,'316,089 identical frame/channel events',transform=a.transAxes,va='top',fontsize=9)
 d=pd.read_csv(SRC/'luke_lowpass_waveform_preservation_v2/per_unit_bin_metrics.csv');d=d[d.support=='original'].groupby('unit_id').template_amplitude_ratio.median();a=ax[1,0];a.bar(np.arange(len(d)),d,color=blue);a.axhline(1,color='black',ls=':');a.set(xticks=np.arange(len(d)),xticklabels=d.index,ylabel='Low-pass / broadband peak amplitude',xlabel='Unit',title='C · Low-pass attenuation differs among cells',ylim=(0,1.12))
 d=pd.read_csv(SRC/'luke_shallow_template_centroid_audit_v4/template_sensitivity_by_shift_gain.csv');d=d[(d.gain==1)&(d.status=='supported')];a=ax[1,1];a.plot(d.requested_shift_um,d.recovered_template_displacement_um,'o-',color=blue,label='Centroid of median waveform');old=pd.read_csv(SRC/'luke_shallow_fractional_calibration_v3/sensitivity_by_shift_gain.csv');old=old[(old.gain==1)&(abs(old.requested_shift_um)<=10)];a.plot(old.requested_shift_um,old.median_recovered_um,'s--',color=pink,label='Median of event changes');a.plot([-10,10],[-10,10],':',color='black',label='Nominal identity');a.set(xlabel='Model injection displacement (µm)',ylabel='Measured change (µm)',title='D · Lighthouse measurement requires calibration');a.legend(fontsize=8);a.text(.03,.97,'Unit154 · approximate interpolation model\nConditional accepted pairs; not physical truth',transform=a.transAxes,va='top',fontsize=8)
 b=pd.read_csv(SRC/'luke_mean_raster_diagnostic_v3/amplitude_sum_cell_metrics.csv').set_index('unit_id');m=pd.read_csv(SRC/'luke_mean_raster_diagnostic_v3/amplitude_mean_cell_metrics.csv').set_index('unit_id');delta=m.overall_mae_um-b.overall_mae_um;a=ax[2,0];a.bar(np.arange(len(delta)),delta,color=[blue if x<0 else pink for x in delta]);a.axhline(0,color='black',lw=.8);a.set(xticks=np.arange(len(delta)),xticklabels=delta.index,xlabel='Unit',ylabel='Mean − sum disagreement (µm)',title='E · Global mean trades shallow gains for deeper losses')
 d=pd.read_csv(SRC/'luke_mean_raster_diagnostic_v3/qualified_unit154_sampling.csv');d=d[d.start_s==4245];real=pd.read_csv(SRC/'luke_shallow_template_centroid_audit_v4/real_median_template_measurements.csv');v=list(d.field_relative_um)+[float(real.loc[real.start_s==4245,'relative_um'].iloc[0])];a=ax[2,1];a.bar(np.arange(3),v,color=[blue,pink,'#555555']);a.set(xticks=np.arange(3),xticklabels=['DREDGE sum','DREDGE mean','Median waveform'],ylabel='Change vs 4240–4245 s (µm)',title='F · Qualified cell supports only part of transition');a.text(.02,.03,'Unit154 at620µm ·49/26 accepted events\nLater bins3/5 events: unsupported\nNo implication for220/410µm region',transform=a.transAxes,va='bottom',fontsize=8,bbox=dict(facecolor='white',alpha=.9,edgecolor='none'))
 fig.suptitle('Motion-estimation checkpoint: keep compensated broadband 3σ amplitude sum\nOne development interval; reference sensitivity and transfer remain unresolved',fontsize=15)
 for ext in ['png','pdf']:fig.savefig(OUT/f'01_prior_round_contact_sheet.{ext}',dpi=130)
 plt.close(fig)
if __name__=='__main__':main()
